name = "BoltzGen"
uuid = "223087a6-b790-4d94-97cd-54b01bafc3a2"
version = "0.1.0"

[deps]
Onion = "fdebf6c2-71da-43a1-b539-c3bc3e09c5c6"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
MoleculeFlow = "0907176b-47b3-4e96-be91-0e9bb91fb14f"

[extensions]
BoltzGenMoleculeFlowExt = "MoleculeFlow"

[compat]
HuggingFaceApi = "0.1"
JLD2 = "0.6"
NNlib = "0.9"
SafeTensors = "1"
YAML = "0.4"
